name: custom-env vriabe

on: [push]

env:
  SUBSCRIBE: Subscribe

jobs:
    Subscribe-my-channel:
        runs-on: ubuntu-latest
        env: 
            LIKE: please like and share 
        steps: 
            - name: "please like and share my channel."    
              run: echo "$LIKE and $SUBSCRIBE our $CHANNEL_NAME channel"

              env:
                CHANNEL_NAME: technical guftgu