name: Run Hello World

on: [push]

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Hello World
      run: echo "Hello, World!"

     
